//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control_Tareas.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<TAREAS> TAREAS { get; set; }
        public DbSet<TAREAS_USUARIOS> TAREAS_USUARIOS { get; set; }
        public DbSet<UNIDAD_INTERNA> UNIDAD_INTERNA { get; set; }
        public DbSet<PERFIL> PERFIL { get; set; }
        public DbSet<PROBLEMAS> PROBLEMAS { get; set; }
    }
}
