//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control_Tareas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAREAS
    {
        public short ID_TAREAS { get; set; }
        public string NOMBRE { get; set; }
        public string ESTADO { get; set; }
        public string DESCRIPCION { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<System.DateTime> FECHADESDE { get; set; }
        public Nullable<System.DateTime> FECHAHASTA { get; set; }
        public Nullable<System.DateTime> FECHACREACION { get; set; }
        public string ESTADO2 { get; set; }
    }
}
