//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control_Tareas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAREAS_USUARIOS
    {
        public short ID { get; set; }
        public Nullable<short> ID_TAREAS { get; set; }
        public Nullable<short> ID_USUARIO { get; set; }
        public string ESTADO { get; set; }
    }
}
