//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control_Tareas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public short ID { get; set; }
        public string NOMBRE { get; set; }
        public string CORREO { get; set; }
        public string PASS { get; set; }
        public Nullable<decimal> PERFIL { get; set; }
        public string APELLIDO { get; set; }
        public string UNIDADINTERNA { get; set; }
    }
}
